# Generated by Django 4.2 on 2023-05-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Publication Date')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Many Articles',
            },
        ),
    ]
